using System;
using System.Collections.Generic;
using System.Linq;

namespace TakingMedications.Services;

/// <summary>
/// Локализация уровня приложения. Аналог Python `med_i18n.T(key, **kwargs)`.
/// Словари RU/EN/UK эмбеддены в код — для v1 не нужен внешний `locales/`.
/// </summary>
public static class Loc
{
    public const string FallbackLang = "ru";

    public static IReadOnlyDictionary<string, string> SupportedLangs { get; } =
        new Dictionary<string, string>
        {
            ["ru"] = "Русский",
            ["uk"] = "Українська",
            ["en"] = "English",
            ["es"] = "Español",
            ["de"] = "Deutsch",
            ["fr"] = "Français",
            ["it"] = "Italiano",
        };

    private static string _lang = FallbackLang;
    public static string CurrentLang => _lang;

    /// <summary>Подписка на смену языка — окна перерисовывают подписи.</summary>
    public static event Action? LanguageChanged;

    public static void SetLang(string lang)
    {
        if (string.IsNullOrEmpty(lang) || !_dictionaries.ContainsKey(lang)) return;
        if (_lang == lang) return;
        _lang = lang;
        LanguageChanged?.Invoke();
    }

    /// <summary>Получить локализованную строку по ключу.</summary>
    public static string T(string key, params (string name, object value)[] args)
    {
        var dict = _dictionaries.TryGetValue(_lang, out var d) ? d : _dictionaries[FallbackLang];
        if (!dict.TryGetValue(key, out var text))
            text = _dictionaries[FallbackLang].GetValueOrDefault(key, key);

        foreach (var (n, v) in args)
            text = text.Replace("{" + n + "}", v?.ToString() ?? "");

        return text;
    }

    // ────────────────────────────────────────────────────────────────────
    //  Словари RU / EN / UK
    // ────────────────────────────────────────────────────────────────────

    private static readonly Dictionary<string, Dictionary<string, string>> _dictionaries = new()
    {
        ["ru"] = new Dictionary<string, string>
        {
            // Общее
            ["app_title"]              = "Приём лекарств",

            // Вкладка «Спросить у ИИ»
            ["tab_ask_ai"]     = "Спросить у ИИ",
            ["ai_question"]    = "Вопрос:",
            ["ai_ask"]         = "▶  Спросить",
            ["ai_save_all"]    = "Сохранить все",
            ["ai_clear"]       = "Очистить",
            ["ai_api_keys"]    = "⚙ API ключи",
            ["ai_save"]        = "Сохранить",
            ["ai_copy"]        = "Копировать",
            ["ai_copied"]      = "Скопировано в буфер",
            ["ai_quick"]       = "Быстрые вопросы:",
            ["ai_qb_compat"]   = "Совместимость",
            ["ai_qb_side"]     = "Побочные эффекты",
            ["ai_qb_time"]     = "Время приёма",
            ["ai_q_compat"]    = "Можно ли принимать эти лекарства вместе и какие возможны взаимодействия? Лекарства: ",
            ["ai_q_side"]      = "Какие основные побочные эффекты у препарата? Препарат: ",
            ["ai_q_time"]      = "В какое время суток и как (до или после еды) лучше принимать препарат? Препарат: ",
            ["ai_empty_title"] = "Вопрос пуст",
            ["ai_empty_msg"]   = "Введите вопрос.",
            ["ai_nothing_msg"] = "Нет ответа для сохранения.",
            ["ai_status_wait"] = "⌛ Жду ответы от ИИ…",
            ["ai_status_done"] = "✓ Готово!",
            ["ai_status_browser"]="🌐 Открыт(ы) в браузере: {list}",
            ["ai_status_none"] = "Нет выбранных ИИ.",
            ["ai_browser_note"]= "🌐 Вопрос открыт в браузере.\nВопрос скопирован в буфер — вставьте (Ctrl+V) в чат.\nСкопируйте ответ сюда после получения.",
            ["ai_req_to"]      = "⌛ Запрос к {name}…",
            ["ai_err"]         = "❌ Ошибка",
            ["ai_stats"]       = "Символов: {chars} | Слов: {words}",
            ["ai_save_header"] = "Ответы ИИ",
            ["ai_keys_title"]  = "API ключи для ИИ",
            ["ai_keys_save"]   = "Сохранить",
            ["ai_key_claude_link"]     = "Получить на console.anthropic.com",
            ["ai_key_gemini_link"]     = "Бесплатно на aistudio.google.com",
            ["ai_key_deepseek_link"]   = "Получить на platform.deepseek.com",
            ["ai_key_perplexity_link"] = "Получить на perplexity.ai/settings/api",

            ["app_data_folder"]        = "Папка данных: {path}",
            ["btn_save"]               = "💾 Сохранить",
            ["btn_cancel"]             = "✕ Отмена",
            ["btn_close"]              = "✕ Закрыть",
            ["btn_edit"]               = "✏ Изменить",
            ["btn_delete"]             = "✕ Удалить",
            ["btn_add"]                = "＋ Добавить",
            ["btn_today"]              = "Сегодня",
            ["btn_now"]                = "Сейчас",
            ["btn_settings"]           = "⚙ Настройки",
            ["btn_pressure"]           = "🩺 Давление",
            ["btn_manage"]             = "📋 Список лекарств",
            ["confirm_title"]          = "Подтверждение",
            ["warning_title"]          = "Внимание",
            ["error_title"]            = "Ошибка",
            ["empty"]                  = "(пусто)",

            // Вкладки
            ["tab_schedule"]           = "Расписание",
            ["tab_history"]            = "История",
            ["tab_finance"]            = "Финансы",
            ["tab_pressure"]           = "Давление",
            ["tab_meds"]               = "Лекарства",

            // Расписание
            ["schedule_empty"]         = "Список пуст — добавьте препараты через «Список лекарств»",
            ["schedule_stats"]         = "Принято: {taken} из {total}",

            // Доп. блоки расписания (примечания + список покупок)
            ["notes_header"]           = "Важные примечания",
            ["notes_empty_hint"]       = "Здесь можно добавить свои важные примечания — нажмите ✎",
            ["purchase_header"]        = "НЕОБХОДИМО ПРИОБРЕСТИ",
            ["purchase_all_ok"]        = "Всё необходимое есть — докупать нечего.",
            ["btn_copy_clipboard"]     = "📋 Копировать список",
            ["purchase_copied"]        = "✓ Скопировано",
            ["schedule_doctor"]        = "врач: {doctor}",
            ["schedule_course"]        = "курс: {course}",
            ["btn_pharmacy"]           = "🔗 Аптеки",
            ["btn_description"]        = "▸ Описание",
            ["course_label"]           = "Курс: {text}",
            ["course_progress"]        = "Курс: начат {start}, день {day} из {total} ({pct}%)",
            ["course_days_left"]       = "ещё {n} дн.",
            ["course_finished"]        = "Курс завершён ({start})",
            ["course_show_btn"]        = "Показать",
            ["course_hide_btn"]        = "Скрыть",
            ["course_start_btn"]       = "▸ Начать курс",
            ["course_extend_btn"]      = "+ ещё дней",
            ["dlg_course_start_title"] = "Начать курс",
            ["dlg_course_start_date"]  = "Дата начала (ДД.ММ.ГГГГ):",
            ["dlg_course_duration"]    = "Длительность (дней):",
            ["dlg_course_dur_invalid"] = "Введите целое положительное число дней.",
            ["dlg_course_extend_title"]= "Продлить курс",
            ["dlg_course_extend_days"] = "Добавить дней:",
            ["stock_available"]        = "В наличии: {n} табл.",
            ["stock_empty"]            = "Закончились ⚠",
            ["stock_not_purchased"]    = "Не куплено ⚠",
            ["taken_no_stock_title"]   = "Нет в наличии",
            ["taken_no_stock_msg"]     = "Нельзя отметить приём: таблетки отсутствуют.\nСначала введите покупку во вкладке «Финансы».",

            // Список лекарств
            ["manage_title"]           = "Список лекарств",
            ["manage_delete_confirm"]  = "Удалить препарат «{name}»?",

            // Редактирование
            ["edit_add_title"]         = "Добавить препарат",
            ["edit_edit_title"]        = "Редактировать: {name}",
            ["edit_section"]           = "Секция:",
            ["edit_time"]              = "Время:",
            ["edit_time_note"]         = "Приём:",
            ["edit_name"]              = "Название:",
            ["edit_subtitle"]          = "Подпись:",
            ["edit_note"]              = "Примечание:",
            ["edit_doctor"]            = "Врач:",
            ["edit_course"]            = "Курс:",
            ["edit_pharmacy"]          = "Аптека/поиск:",
            ["edit_id"]                = "ID:",
            ["edit_description"]       = "Описание:",
            ["edit_name_required"]     = "Заполните «Название».",

            // Настройки
            ["settings_title"]               = "Настройки",
            ["settings_language"]            = "Язык интерфейса:",
            ["settings_patient_name"]        = "Имя пациента:",
            ["settings_lang_note"]           = "Изменения применяются мгновенно.",
            ["settings_patient_section"]     = "Пациент",
            ["settings_patient_fio"]         = "ФИО:",
            ["settings_patient_dob"]         = "Дата рождения:",
            ["settings_patient_gender"]      = "Пол:",
            ["settings_patient_male"]        = "Мужской",
            ["settings_patient_female"]      = "Женский",
            ["settings_manage_patients"]     = "👥 Управление пациентами",
            ["settings_app_mode_section"]    = "Режим запуска",
            ["settings_mode_window"]         = "Только окно",
            ["settings_mode_window_desc"]    = "Приложение работает только пока открыто. Закрытие завершает работу.",
            ["settings_mode_tray"]           = "Свернуть в трей",
            ["settings_mode_tray_desc"]      = "Закрытие сворачивает в трей. Напоминания работают в фоне.",
            ["settings_mode_autostart"]      = "Автозапуск Windows",
            ["settings_mode_autostart_desc"] = "Запускается при входе в Windows. Работает в трее.",
            ["settings_mode_hidden"]         = "Только в фоне",
            ["settings_mode_hidden_desc"]    = "Запускается скрыто, только в трее. Окно не открывается.",
            ["settings_feature_wip"]         = "Функция в разработке",
            ["settings_theme_section"]       = "Тема оформления",
            ["settings_theme_dark"]          = "🌙 Тёмная",
            ["settings_theme_light"]         = "☀ Светлая (Windows)",

            // Прогноз и покупки
            ["tab_forecast"]            = "📦 Запас",
            ["forecast_title"]          = "📦 Прогноз запаса лекарств",
            ["forecast_subtitle"]       = "Сколько дней осталось по текущему запасу",
            ["forecast_no_data"]        = "Нет данных о запасах. Введите количество таблеток в карточке препарата.",
            ["forecast_col_name"]       = "Препарат",
            ["forecast_col_stock"]      = "Запас",
            ["forecast_col_daily"]      = "В день",
            ["forecast_col_days"]       = "Осталось",
            ["forecast_days"]           = "дн.",
            ["shopping_title"]          = "🛒 Список покупок",
            ["shopping_subtitle"]       = "Препараты, которых осталось менее чем на 2 недели",
            ["shopping_all_ok"]         = "✅ Все препараты в наличии на ближайшие 2 недели",
            ["shopping_depleted"]       = "закончились!",
            ["shopping_days_left"]      = "осталось {n} дн.",

            // Документы
            ["tab_documents"]           = "📁 Документы",
            ["documents_title"]         = "📁 Медицинские документы",
            ["documents_open_folder"]   = "📂 Открыть папку",
            ["documents_empty"]         = "Папка документов пуста. Добавьте PDF, изображения или другие файлы.",
            ["documents_no_folder"]     = "Папка документов не найдена.",
            ["documents_delete_confirm"] = "Удалить файл «{name}»?",
            ["documents_add_file"]      = "➕ Добавить файл",
            ["documents_refresh_tip"]   = "Обновить список",

            // Напоминания
            ["settings_reminders_section"]   = "🔔 Напоминания",
            ["settings_reminders_visual"]    = "Показывать напоминания о приёме лекарств",
            ["settings_reminders_visual_desc"] = "Уведомления появляются за несколько минут до приёма. При пропуске или после сна ПК — показывается сводка пропущенных.",
            ["settings_reminders_voice"]     = "🔊 Голосовые напоминания",
            ["settings_reminders_voice_desc"] = "Произносить вслух название препарата при наступлении времени приёма. Работает независимо от визуальных уведомлений.",
            ["settings_voice_label"]         = "Голос:",
            ["settings_voice_test"]          = "🔊 Тест",
            ["settings_voice_auto"]          = "(авто)",
            ["settings_voice_test_text"]     = "Время принять лекарства",

            // Telegram
            ["settings_tg_section"]          = "📨 Дублирование в Telegram",
            ["settings_tg_enable"]           = "Присылать те же напоминания в Telegram",
            ["settings_tg_enable_desc"]      = "Удобно, если ПК выключен или вы не рядом с ним. Понадобится Telegram-бот и ID вашего чата с ботом.",
            ["settings_tg_token_label"]      = "Bot Token:",
            ["settings_tg_how"]             = "❓ Как создать бота?",
            ["settings_tg_how_url"]          = "https://t.me/BotFather",
            ["settings_tg_connect"]          = "🔗 Подключить Telegram",
            ["settings_tg_disconnect"]       = "Отключить",
            ["settings_tg_test"]             = "Отправить «Привет»",
            ["settings_tg_connected"]        = "✔ подключено",
            ["settings_tg_not_connected"]    = "не подключено",
            ["settings_tg_id_label"]         = " · ID ",
            ["settings_tg_connecting"]       = "Отправьте любое сообщение боту @{bot} и нажмите ОК.",
            ["settings_tg_connect_ok"]       = "Подключено! Chat ID: {id}",
            ["settings_tg_connect_fail"]     = "Не удалось получить chat ID. Убедитесь, что отправили сообщение боту.",
            ["settings_tg_token_invalid"]    = "Неверный Bot Token. Проверьте значение.",
            ["settings_tg_test_ok"]          = "Сообщение отправлено!",
            ["settings_tg_test_fail"]        = "Не удалось отправить. Проверьте подключение.",

            // Внешний вид
            ["settings_appearance_section"]  = "🎨 Внешний вид",
            ["settings_border_label"]        = "Цвет границ между блоками:",
            ["settings_border_light"]        = "Светлые",
            ["settings_border_medium"]       = "Средние",
            ["settings_border_dark"]         = "Тёмные",
            ["settings_border_desc"]         = "Влияет на разделительные линии между карточками препаратов.",

            // Обновления
            ["settings_update_section"]  = "🔄 Обновления",
            ["settings_update_check"]    = "🔍 Проверить обновления",
            ["settings_update_uptodate"] = "Установлена последняя версия.",
            ["settings_update_failed"]   = "Не удалось проверить. Проверьте подключение.",

            // АД
            ["pressure_title"]         = "Артериальное давление",
            ["pressure_header"]        = "Артериальное давление  {date}",
            ["pressure_pulse"]         = "Пульс",
            ["pressure_sys"]           = "Систолическое",
            ["pressure_dia"]           = "Диастолическое",
            ["pressure_save"]          = "Сохранить",
            ["pressure_history"]       = "История измерений",
            ["pressure_no_records"]    = "Записей пока нет",
            ["pressure_invalid_sys"]   = "Систолическое (sys): целое 60–260.",
            ["pressure_invalid_dia"]   = "Диастолическое (dia): целое 30–180.",
            ["pressure_invalid_pulse"] = "Пульс: целое 30–220 (или пусто).",
            ["pressure_out_of_range"]  = "Значения вне обычного диапазона. Сохранить всё равно?",
            ["pressure_delete_confirm"]  = "Удалить запись от {ts}?",
            ["pressure_sugar"]           = "Сахар",
            ["pressure_invalid_sugar"]   = "Сахар: число 1.0–30.0 ммоль/л (или пусто).",
            ["pressure_sugar_unusual"]   = "Сахар вне обычного диапазона (3–20 ммоль/л). Сохранить?",
            ["pressure_tab_history"]     = "История",
            ["pressure_tab_chart"]       = "График",
            ["pressure_delete_selected"] = "✕ Удалить выбранную",
            ["pressure_no_selection"]    = "Выберите строку для удаления",
            ["pressure_col_datetime"]    = "Дата/время",
            ["pressure_col_sys"]         = "Сист.",
            ["pressure_col_dia"]         = "Диаст.",
            ["pressure_col_pulse"]       = "Пульс",
            ["pressure_col_sugar"]       = "Сахар",
            ["pressure_col_category"]    = "Категория",
            ["pressure_chart_no_data"]   = "Недостаточно данных для графика (нужно ≥ 2 записей)",
            ["pressure_chart_sys"]       = "Систолическое",
            ["pressure_chart_dia"]       = "Диастолическое",
            ["pressure_chart_pulse"]     = "Пульс",
            ["pressure_bp_optimal"]      = "Оптимальное",

            // Календарь / история
            ["history_tab_calendar"]   = "История",
            ["history_tab_charts"]     = "График",
            ["history_chart_adherence"] = "Приём лекарств по месяцам (%)",
            ["history_chart_pressure"] = "Артериальное давление (последние измерения)",
            ["history_legend_full"]    = "Все приняты",
            ["history_legend_partial"] = "Частично",
            ["history_legend_empty"]   = "Пропущено",
            ["history_legend_none"]    = "Нет данных",
            ["history_select_day"]     = "Выберите день в календаре",
            ["history_day_taken"]      = "Принято: {taken} из {total}",
            ["history_day_no_data"]    = "За {date} отметок нет.",

            // Финансы (таблица Excel-style)
            ["finance_total"]          = "Итого",
            ["finance_total_value"]    = "Итого за весь период: {amount}",
            ["finance_per_med"]        = "По препаратам",
            ["finance_purchases"]      = "Покупки",
            ["finance_no_purchases"]   = "Покупок пока нет",
            ["finance_add_purchase"]   = "＋ Добавить покупку",
            ["finance_date"]           = "Дата:",
            ["finance_med"]            = "Препарат:",
            ["finance_amount"]         = "Сумма:",
            ["finance_note"]           = "Примечание:",
            ["finance_amount_required"]= "Сумма должна быть положительным числом.",
            ["finance_med_required"]   = "Выберите препарат.",
            ["finance_delete_confirm"] = "Удалить покупку «{name}» от {date}?",
            ["fin_col_no"]             = "No",
            ["fin_col_med"]            = "Препарат",
            ["fin_col_total"]          = "Итого",
            ["fin_currency"]           = "₴",
            ["fin_units"]              = "шт",
            ["fin_total_by_date"]      = "Итого по дате",
            ["fin_grand_label"]        = "Итого: {amount} {currency}",
            ["fin_grand_label_cnt"]    = "  ({cnt} шт)",
            ["fin_plan_note"]          = "Это план/оценка. Фактические расходы — в блоке выше, из «Денег».",
            ["fin_actual_title"]       = "Фактические расходы на лекарства (из «Денег»)",
            ["fin_actual_total"]       = "потрачено: {amount} {currency}",
            ["fin_actual_empty"]       = "Записей нет. Расходы ведутся в программе «Деньги» (категория «Аптека»).",
            ["fin_actual_no_money"]    = "Программа «Деньги» не установлена — фактические расходы недоступны. Здесь можно только планировать.",
            ["fin_actual_open_money"]  = "Открыть «Деньги»",
            ["fin_actual_hdr_date"]    = "Дата",
            ["fin_actual_hdr_name"]    = "Препарат / статья",
            ["fin_actual_hdr_account"] = "Счёт",
            ["fin_actual_hdr_amount"]  = "Сумма",
            ["fin_actual_more"]        = "…и ещё {n} записей (показаны последние 100).",
            ["fin_no_meds"]            = "Добавьте лекарства в расписание — они появятся здесь",
            ["fin_no_dates"]           = "Нажмите «Добавить дату» для начала",
            ["btn_add_date"]           = "＋ Добавить дату",
            ["btn_del_last"]           = "✕ Удалить последнюю",
            ["dlg_add_date_title"]     = "Добавить дату",
            ["dlg_add_date_label"]     = "Дата (ДД.ММ.ГГГГ):",
            ["dlg_add_date_empty"]     = "Введите дату.",
            ["dlg_add_date_dup"]       = "Дата {val} уже есть в таблице.",
            ["dlg_add_date_invalid"]   = "Неверный формат. Используйте ДД.ММ.ГГГГ (пр.: 15.04.2026).",
            ["fin_no_data"]            = "Нет данных",
            ["fin_no_dates_msg"]       = "Нет дат для удаления.",
            ["fin_del_col_title"]      = "Удалить последнюю дату?",
            ["fin_del_col_msg"]        = "Удалить столбец {date}?",
            ["fin_del_col_filled"]     = "В этой колонке заполнено строк: {n}.",
            ["fin_del_col_empty"]      = "Колонка пустая — данных за этот день нет.",

            // PDF-отчёт
            ["btn_export_pdf"]         = "📄 Отчёт PDF",
            ["pdf_title"]              = "Отчёт по приёму лекарств",
            ["pdf_period"]             = "{from} — {to}",
            ["pdf_footer_generated"]   = "Сгенерировано:",
            ["pdf_section_summary"]    = "Сводка за период",
            ["pdf_section_schedule"]   = "Список препаратов",
            ["pdf_section_history"]    = "История приёма",
            ["pdf_section_pressure"]   = "Артериальное давление",
            ["pdf_section_finance"]    = "Расходы",
            ["pdf_history_per_med"]    = "По препаратам",
            ["pdf_stat_days_full"]     = "дней — все приняты",
            ["pdf_stat_days_partial"]  = "дней — частично",
            ["pdf_stat_days_empty"]    = "дней — пропуск/нет данных",
            ["pdf_stat_overall"]       = "общий % приёма",
            ["pdf_pressure_avg_sys"]   = "ср. систолическое",
            ["pdf_pressure_avg_dia"]   = "ср. диастолическое",
            ["pdf_pressure_avg_pulse"] = "ср. пульс",
            ["pdf_pressure_count"]     = "всего измерений",
            ["pdf_pressure_category"]  = "категория",
            ["pdf_col_time"]           = "Время",
            ["pdf_col_med"]            = "Препарат",
            ["pdf_col_doctor"]         = "Врач",
            ["pdf_col_course"]         = "Курс",
            ["pdf_col_date"]           = "Дата",
            ["pdf_col_when"]           = "Дата/время",
            ["pdf_col_taken"]          = "Принято",
            ["pdf_col_percent"]        = "%",
            ["pdf_col_visual"]         = "Визуально",
            ["pdf_col_count"]          = "Кол-во",
            ["pdf_col_amount"]         = "Сумма",
            ["pdf_bp_normal"]          = "норма",
            ["pdf_bp_normal_high"]     = "норм.повышенное",
            ["pdf_bp_high_normal"]     = "выс.нормальное",
            ["pdf_bp_stage1"]          = "АГ I ст.",
            ["pdf_bp_stage2"]          = "АГ II ст.",
            ["pdf_bp_crisis"]          = "криз",

            // Диалог экспорта
            ["export_title"]           = "Экспорт PDF-отчёта",
            ["export_period"]          = "Период:",
            ["export_from"]            = "С:",
            ["export_to"]              = "По:",
            ["export_include"]         = "Включить:",
            ["export_inc_schedule"]    = "Список препаратов",
            ["export_inc_history"]     = "История приёма",
            ["export_inc_pressure"]    = "Давление",
            ["export_inc_finance"]     = "Финансы",
            ["export_path"]            = "Файл:",
            ["export_browse"]          = "Обзор…",
            ["export_default_name"]    = "MedReport_{from}_{to}.pdf",
            ["export_open_after"]      = "Открыть после сохранения",
            ["export_btn_save"]        = "💾 Сохранить PDF",
            ["export_quick_7"]         = "7 дней",
            ["export_quick_30"]        = "30 дней",
            ["export_quick_90"]        = "90 дней",
            ["export_quick_year"]      = "Год",
            ["export_done"]            = "PDF сохранён: {path}",
            ["export_error"]           = "Не удалось сохранить PDF: {err}",

            // Взаимодействия лекарств
            ["btn_interactions"]               = "⚠ Взаимодействия",
            ["interactions_title"]             = "Взаимодействия лекарств",
            ["interactions_disclaimer"]        = "⚠ ЭТО НЕ МЕДИЦИНСКАЯ КОНСУЛЬТАЦИЯ. Таблица содержит только хорошо задокументированные взаимодействия из открытых источников. Она неполна и не учитывает дозы, сопутствующие заболевания или индивидуальные риски. Отсутствие пары в таблице НЕ означает, что взаимодействия нет. Всегда консультируйтесь с врачом или фармацевтом.",
            ["interactions_summary"]           = "Препаратов: {n_meds}. Проверено пар: {n_pairs} по {n_rules} правилам. Совпадений: {n_hits}.",
            ["interactions_none"]              = "✅ Известных взаимодействий не найдено.",
            ["interactions_sev_high"]          = "ВЫСОКИЙ",
            ["interactions_sev_medium"]        = "Средний",
            ["interactions_sev_info"]          = "Инфо",

            // Напоминания
            ["btn_reminders"]                  = "🔔 Напоминания",
            ["reminder_on"]                    = "🔔 Напоминания ВКЛ",
            ["reminder_off"]                   = "🔕 Напоминания ВЫКЛ",
            ["reminder_toast_title"]           = "Время принять лекарства ({time})",
            ["reminder_toast_msg"]             = "Пора принять:\n{names}",
            ["reminder_missed_title"]          = "Пропущенные приёмы",
            ["reminder_missed_msg"]            = "Пропущено сегодня:\n{lines}",
            ["settings_reminders"]             = "Напоминания:",
            ["settings_reminders_note"]        = "Уведомления о приёме лекарств по расписанию.",

            // Трей
            ["tray_show"]                      = "Показать",
            ["tray_exit"]                      = "Выход",
            ["tray_hidden_hint"]               = "Приложение свёрнуто в трей. Двойной клик для открытия.",

            // Заметки
            ["btn_notes"]                      = "📝 Заметки",
            ["notes_title"]                    = "Заметки",
            ["notes_empty"]                    = "Заметок пока нет",
            ["notes_add_placeholder"]          = "Новая заметка…",
            ["notes_delete_confirm"]           = "Удалить заметку?",
            ["notes_color_none"]               = "Нет",
            ["notes_color_yellow"]             = "Жёлтый",
            ["notes_color_green"]              = "Зелёный",
            ["notes_color_red"]                = "Красный",
            ["notes_color_blue"]               = "Синий",

            // Дни недели и месяцы (родительный падеж для дат)
            ["weekday_short_0"]        = "Пн",
            ["weekday_short_1"]        = "Вт",
            ["weekday_short_2"]        = "Ср",
            ["weekday_short_3"]        = "Чт",
            ["weekday_short_4"]        = "Пт",
            ["weekday_short_5"]        = "Сб",
            ["weekday_short_6"]        = "Вс",
            ["weekday_full_0"]         = "понедельник",
            ["weekday_full_1"]         = "вторник",
            ["weekday_full_2"]         = "среда",
            ["weekday_full_3"]         = "четверг",
            ["weekday_full_4"]         = "пятница",
            ["weekday_full_5"]         = "суббота",
            ["weekday_full_6"]         = "воскресенье",
            ["month_gen_1"]            = "января",
            ["month_gen_2"]            = "февраля",
            ["month_gen_3"]            = "марта",
            ["month_gen_4"]            = "апреля",
            ["month_gen_5"]            = "мая",
            ["month_gen_6"]            = "июня",
            ["month_gen_7"]            = "июля",
            ["month_gen_8"]            = "августа",
            ["month_gen_9"]            = "сентября",
            ["month_gen_10"]           = "октября",
            ["month_gen_11"]           = "ноября",
            ["month_gen_12"]           = "декабря",
            ["month_nom_1"]            = "Январь",
            ["month_nom_2"]            = "Февраль",
            ["month_nom_3"]            = "Март",
            ["month_nom_4"]            = "Апрель",
            ["month_nom_5"]            = "Май",
            ["month_nom_6"]            = "Июнь",
            ["month_nom_7"]            = "Июль",
            ["month_nom_8"]            = "Август",
            ["month_nom_9"]            = "Сентябрь",
            ["month_nom_10"]           = "Октябрь",
            ["month_nom_11"]           = "Ноябрь",
            ["month_nom_12"]           = "Декабрь",
        },

        ["en"] = new Dictionary<string, string>
        {
            ["app_title"]              = "Taking Medications",

            // Ask-AI tab
            ["tab_ask_ai"]     = "Ask AI",
            ["ai_question"]    = "Question:",
            ["ai_ask"]         = "▶  Ask",
            ["ai_save_all"]    = "Save all",
            ["ai_clear"]       = "Clear",
            ["ai_api_keys"]    = "⚙ API keys",
            ["ai_save"]        = "Save",
            ["ai_copy"]        = "Copy",
            ["ai_copied"]      = "Copied to clipboard",
            ["ai_quick"]       = "Quick questions:",
            ["ai_qb_compat"]   = "Compatibility",
            ["ai_qb_side"]     = "Side effects",
            ["ai_qb_time"]     = "When to take",
            ["ai_q_compat"]    = "Can these medications be taken together, and what interactions are possible? Medications: ",
            ["ai_q_side"]      = "What are the main side effects of this medication? Medication: ",
            ["ai_q_time"]      = "At what time of day and how (before or after meals) is it best to take this medication? Medication: ",
            ["ai_empty_title"] = "Empty question",
            ["ai_empty_msg"]   = "Enter a question.",
            ["ai_nothing_msg"] = "No answer to save.",
            ["ai_status_wait"] = "⌛ Waiting for AI…",
            ["ai_status_done"] = "✓ Done!",
            ["ai_status_browser"]="🌐 Opened in browser: {list}",
            ["ai_status_none"] = "No AI selected.",
            ["ai_browser_note"]= "🌐 Question opened in the browser.\nIt is copied to the clipboard — paste (Ctrl+V) into the chat.\nCopy the answer back here.",
            ["ai_req_to"]      = "⌛ Request to {name}…",
            ["ai_err"]         = "❌ Error",
            ["ai_stats"]       = "Chars: {chars} | Words: {words}",
            ["ai_save_header"] = "AI answers",
            ["ai_keys_title"]  = "API keys for AI",
            ["ai_keys_save"]   = "Save",
            ["ai_key_claude_link"]     = "Get it at console.anthropic.com",
            ["ai_key_gemini_link"]     = "Free at aistudio.google.com",
            ["ai_key_deepseek_link"]   = "Get it at platform.deepseek.com",
            ["ai_key_perplexity_link"] = "Get it at perplexity.ai/settings/api",

            ["app_data_folder"]        = "Data folder: {path}",
            ["btn_save"]               = "💾 Save",
            ["btn_cancel"]             = "✕ Cancel",
            ["btn_close"]              = "✕ Close",
            ["btn_edit"]               = "✏ Edit",
            ["btn_delete"]             = "✕ Delete",
            ["btn_add"]                = "＋ Add",
            ["btn_today"]              = "Today",
            ["btn_now"]                = "Now",
            ["btn_settings"]           = "⚙ Settings",
            ["btn_pressure"]           = "🩺 Pressure",
            ["btn_manage"]             = "📋 Medications",
            ["confirm_title"]          = "Confirm",
            ["warning_title"]          = "Warning",
            ["error_title"]            = "Error",
            ["empty"]                  = "(empty)",

            ["tab_schedule"]           = "Schedule",
            ["tab_history"]            = "History",
            ["tab_finance"]            = "Finance",
            ["tab_pressure"]           = "Pressure",
            ["tab_meds"]               = "Medications",

            ["schedule_empty"]         = "Empty list — add medications via the «Medications» button",
            ["schedule_stats"]         = "Taken: {taken} of {total}",

            // Schedule extra blocks (notes + shopping list)
            ["notes_header"]           = "Important notes",
            ["notes_empty_hint"]       = "You can add your important notes here — click ✎",
            ["purchase_header"]        = "NEED TO BUY",
            ["purchase_all_ok"]        = "Everything is in stock — nothing to buy.",
            ["btn_copy_clipboard"]     = "📋 Copy list",
            ["purchase_copied"]        = "✓ Copied",
            ["schedule_doctor"]        = "doctor: {doctor}",
            ["schedule_course"]        = "course: {course}",
            ["btn_pharmacy"]           = "🔗 Pharmacies",
            ["btn_description"]        = "▸ Description",
            ["course_label"]           = "Course: {text}",
            ["course_progress"]        = "Course: started {start}, day {day} of {total} ({pct}%)",
            ["course_days_left"]       = "{n} days left",
            ["course_finished"]        = "Course finished ({start})",
            ["course_show_btn"]        = "Show",
            ["course_hide_btn"]        = "Hide",
            ["course_start_btn"]       = "▸ Start course",
            ["course_extend_btn"]      = "+ more days",
            ["dlg_course_start_title"] = "Start course",
            ["dlg_course_start_date"]  = "Start date (DD.MM.YYYY):",
            ["dlg_course_duration"]    = "Duration (days):",
            ["dlg_course_dur_invalid"] = "Enter a positive integer number of days.",
            ["dlg_course_extend_title"]= "Extend course",
            ["dlg_course_extend_days"] = "Add days:",
            ["stock_available"]        = "In stock: {n} pcs.",
            ["stock_empty"]            = "Ran out ⚠",
            ["stock_not_purchased"]    = "Not purchased ⚠",
            ["taken_no_stock_title"]   = "Not in stock",
            ["taken_no_stock_msg"]     = "Cannot mark as taken: medication is not in stock.\nPlease add a purchase in the Finance tab first.",

            ["manage_title"]           = "Medications",
            ["manage_delete_confirm"]  = "Delete medication «{name}»?",

            ["edit_add_title"]         = "Add medication",
            ["edit_edit_title"]        = "Edit: {name}",
            ["edit_section"]           = "Section:",
            ["edit_time"]              = "Time:",
            ["edit_time_note"]         = "Intake:",
            ["edit_name"]              = "Name:",
            ["edit_subtitle"]          = "Subtitle:",
            ["edit_note"]              = "Note:",
            ["edit_doctor"]            = "Doctor:",
            ["edit_course"]            = "Course:",
            ["edit_pharmacy"]          = "Pharmacy/search:",
            ["edit_id"]                = "ID:",
            ["edit_description"]       = "Description:",
            ["edit_name_required"]     = "Please fill in «Name».",

            ["settings_title"]               = "Settings",
            ["settings_language"]            = "Interface language:",
            ["settings_patient_name"]        = "Patient name:",
            ["settings_lang_note"]           = "Changes apply instantly.",
            ["settings_patient_section"]     = "Patient",
            ["settings_patient_fio"]         = "Full name:",
            ["settings_patient_dob"]         = "Date of birth:",
            ["settings_patient_gender"]      = "Gender:",
            ["settings_patient_male"]        = "Male",
            ["settings_patient_female"]      = "Female",
            ["settings_manage_patients"]     = "👥 Manage patients",
            ["settings_app_mode_section"]    = "Startup mode",
            ["settings_mode_window"]         = "Window only",
            ["settings_mode_window_desc"]    = "App runs only while the window is open. Closing exits the app.",
            ["settings_mode_tray"]           = "Minimize to tray",
            ["settings_mode_tray_desc"]      = "Closing minimizes to system tray. Reminders work in background.",
            ["settings_mode_autostart"]      = "Windows autostart",
            ["settings_mode_autostart_desc"] = "Starts with Windows. Runs in system tray.",
            ["settings_mode_hidden"]         = "Background only",
            ["settings_mode_hidden_desc"]    = "Starts hidden, in tray only. No window on startup.",
            ["settings_feature_wip"]         = "Feature in development",
            ["settings_theme_section"]       = "Appearance theme",
            ["settings_theme_dark"]          = "🌙 Dark",
            ["settings_theme_light"]         = "☀ Light (Windows)",

            ["settings_reminders_section"]   = "🔔 Reminders",
            ["settings_reminders_visual"]    = "Show medication reminders",
            ["settings_reminders_visual_desc"] = "Notifications appear a few minutes before each dose. If missed or after PC sleep — a summary of missed doses is shown.",
            ["settings_reminders_voice"]     = "🔊 Voice reminders",
            ["settings_reminders_voice_desc"] = "Read the medication name aloud when dose time arrives. Works independently of visual notifications.",
            ["settings_voice_label"]         = "Voice:",
            ["settings_voice_test"]          = "🔊 Test",
            ["settings_voice_auto"]          = "(auto)",
            ["settings_voice_test_text"]     = "Time to take your medication",
            ["settings_tg_section"]          = "📨 Telegram notifications",
            ["settings_tg_enable"]           = "Send the same reminders via Telegram",
            ["settings_tg_enable_desc"]      = "Useful when PC is off or you're away. Requires a Telegram bot and your chat ID.",
            ["settings_tg_token_label"]      = "Bot Token:",
            ["settings_tg_how"]             = "❓ How to create a bot?",
            ["settings_tg_how_url"]          = "https://t.me/BotFather",
            ["settings_tg_connect"]          = "🔗 Connect Telegram",
            ["settings_tg_disconnect"]       = "Disconnect",
            ["settings_tg_test"]             = "Send «Hello»",
            ["settings_tg_connected"]        = "✔ connected",
            ["settings_tg_not_connected"]    = "not connected",
            ["settings_tg_id_label"]         = " · ID ",
            ["settings_tg_connecting"]       = "Send any message to bot @{bot} and click OK.",
            ["settings_tg_connect_ok"]       = "Connected! Chat ID: {id}",
            ["settings_tg_connect_fail"]     = "Could not get chat ID. Make sure you sent a message to the bot.",
            ["settings_tg_token_invalid"]    = "Invalid Bot Token. Please check the value.",
            ["settings_tg_test_ok"]          = "Message sent!",
            ["settings_tg_test_fail"]        = "Could not send. Check your connection.",
            ["settings_appearance_section"]  = "🎨 Appearance",
            ["settings_border_label"]        = "Border color between blocks:",
            ["settings_border_light"]        = "Light",
            ["settings_border_medium"]       = "Medium",
            ["settings_border_dark"]         = "Dark",
            ["settings_border_desc"]         = "Affects the separator lines between medication cards.",

            ["settings_update_section"]  = "🔄 Updates",
            ["settings_update_check"]    = "🔍 Check for updates",
            ["settings_update_uptodate"] = "You have the latest version.",
            ["settings_update_failed"]   = "Could not check. Please verify your connection.",

            ["pressure_title"]         = "Blood pressure",
            ["pressure_header"]        = "Blood pressure  {date}",
            ["pressure_pulse"]         = "Pulse",
            ["pressure_sys"]           = "Systolic",
            ["pressure_dia"]           = "Diastolic",
            ["pressure_save"]          = "Save",
            ["pressure_history"]       = "Measurement history",
            ["pressure_no_records"]    = "No records yet",
            ["pressure_invalid_sys"]   = "Systolic (sys): integer 60–260.",
            ["pressure_invalid_dia"]   = "Diastolic (dia): integer 30–180.",
            ["pressure_invalid_pulse"] = "Pulse: integer 30–220 (or empty).",
            ["pressure_out_of_range"]  = "Values are out of the usual range. Save anyway?",
            ["pressure_delete_confirm"]  = "Delete record from {ts}?",
            ["pressure_sugar"]           = "Sugar",
            ["pressure_invalid_sugar"]   = "Sugar: number 1.0–30.0 mmol/L (or empty).",
            ["pressure_sugar_unusual"]   = "Sugar is outside the normal range (3–20 mmol/L). Save anyway?",
            ["pressure_tab_history"]     = "History",
            ["pressure_tab_chart"]       = "Chart",
            ["pressure_delete_selected"] = "✕ Delete selected",
            ["pressure_no_selection"]    = "Select a row to delete",
            ["pressure_col_datetime"]    = "Date/time",
            ["pressure_col_sys"]         = "Sys.",
            ["pressure_col_dia"]         = "Dia.",
            ["pressure_col_pulse"]       = "Pulse",
            ["pressure_col_sugar"]       = "Sugar",
            ["pressure_col_category"]    = "Category",
            ["pressure_chart_no_data"]   = "Not enough data for chart (need ≥ 2 records)",
            ["pressure_chart_sys"]       = "Systolic",
            ["pressure_chart_dia"]       = "Diastolic",
            ["pressure_chart_pulse"]     = "Pulse",
            ["pressure_bp_optimal"]      = "Optimal",

            ["history_tab_calendar"]   = "History",
            ["history_tab_charts"]     = "Charts",
            ["history_chart_adherence"] = "Medication adherence by month (%)",
            ["history_chart_pressure"] = "Blood pressure (latest readings)",
            ["history_legend_full"]    = "All taken",
            ["history_legend_partial"] = "Partial",
            ["history_legend_empty"]   = "Missed",
            ["history_legend_none"]    = "No data",
            ["history_select_day"]     = "Pick a day in the calendar",
            ["history_day_taken"]      = "Taken: {taken} of {total}",
            ["history_day_no_data"]    = "No marks for {date}.",

            ["finance_total"]          = "Total",
            ["finance_total_value"]    = "Grand total: {amount}",
            ["finance_per_med"]        = "Per medication",
            ["finance_purchases"]      = "Purchases",
            ["finance_no_purchases"]   = "No purchases yet",
            ["finance_add_purchase"]   = "＋ Add purchase",
            ["finance_date"]           = "Date:",
            ["finance_med"]            = "Medication:",
            ["finance_amount"]         = "Amount:",
            ["finance_note"]           = "Note:",
            ["finance_amount_required"]= "Amount must be a positive number.",
            ["finance_med_required"]   = "Select a medication.",
            ["finance_delete_confirm"] = "Delete purchase «{name}» from {date}?",
            ["fin_col_no"]             = "No",
            ["fin_col_med"]            = "Medication",
            ["fin_col_total"]          = "Total",
            ["fin_currency"]           = "₴",
            ["fin_units"]              = "pcs",
            ["fin_total_by_date"]      = "Total by date",
            ["fin_grand_label"]        = "Total: {amount} {currency}",
            ["fin_grand_label_cnt"]    = "  ({cnt} pcs)",
            ["fin_plan_note"]          = "This is a plan/estimate. Actual expenses are shown above, from “Money”.",
            ["fin_actual_title"]       = "Actual medication expenses (from “Money”)",
            ["fin_actual_total"]       = "spent: {amount} {currency}",
            ["fin_actual_empty"]       = "No records. Expenses are kept in the “Money” app (category Pharmacy).",
            ["fin_actual_no_money"]    = "The “Money” app is not installed — actual expenses are unavailable. You can only plan here.",
            ["fin_actual_open_money"]  = "Open “Money”",
            ["fin_actual_hdr_date"]    = "Date",
            ["fin_actual_hdr_name"]    = "Medication / item",
            ["fin_actual_hdr_account"] = "Account",
            ["fin_actual_hdr_amount"]  = "Amount",
            ["fin_actual_more"]        = "…and {n} more records (latest 100 shown).",
            ["fin_no_meds"]            = "Add medications to the schedule — they will appear here",
            ["fin_no_dates"]           = "Press «Add date» to begin",
            ["btn_add_date"]           = "＋ Add date",
            ["btn_del_last"]           = "✕ Delete last",
            ["dlg_add_date_title"]     = "Add date",
            ["dlg_add_date_label"]     = "Date (DD.MM.YYYY):",
            ["dlg_add_date_empty"]     = "Please enter a date.",
            ["dlg_add_date_dup"]       = "Date {val} already exists.",
            ["dlg_add_date_invalid"]   = "Invalid format. Use DD.MM.YYYY (e.g. 15.04.2026).",
            ["fin_no_data"]            = "No data",
            ["fin_no_dates_msg"]       = "No dates to delete.",
            ["fin_del_col_title"]      = "Delete last date?",
            ["fin_del_col_msg"]        = "Delete column {date}?",
            ["fin_del_col_filled"]     = "Filled rows in this column: {n}.",
            ["fin_del_col_empty"]      = "Column is empty — no data for this day.",

            ["btn_export_pdf"]         = "📄 PDF Report",
            ["pdf_title"]              = "Medication Intake Report",
            ["pdf_period"]             = "{from} — {to}",
            ["pdf_footer_generated"]   = "Generated:",
            ["pdf_section_summary"]    = "Period summary",
            ["pdf_section_schedule"]   = "Medication list",
            ["pdf_section_history"]    = "Intake history",
            ["pdf_section_pressure"]   = "Blood pressure",
            ["pdf_section_finance"]    = "Expenses",
            ["pdf_history_per_med"]    = "Per medication",
            ["pdf_stat_days_full"]     = "days — all taken",
            ["pdf_stat_days_partial"]  = "days — partial",
            ["pdf_stat_days_empty"]    = "days — missed/no data",
            ["pdf_stat_overall"]       = "overall %",
            ["pdf_pressure_avg_sys"]   = "avg systolic",
            ["pdf_pressure_avg_dia"]   = "avg diastolic",
            ["pdf_pressure_avg_pulse"] = "avg pulse",
            ["pdf_pressure_count"]     = "total readings",
            ["pdf_pressure_category"]  = "category",
            ["pdf_col_time"]           = "Time",
            ["pdf_col_med"]            = "Medication",
            ["pdf_col_doctor"]         = "Doctor",
            ["pdf_col_course"]         = "Course",
            ["pdf_col_date"]           = "Date",
            ["pdf_col_when"]           = "Date/time",
            ["pdf_col_taken"]          = "Taken",
            ["pdf_col_percent"]        = "%",
            ["pdf_col_visual"]         = "Visual",
            ["pdf_col_count"]          = "Count",
            ["pdf_col_amount"]         = "Amount",
            ["pdf_bp_normal"]          = "normal",
            ["pdf_bp_normal_high"]     = "normal high",
            ["pdf_bp_high_normal"]     = "high normal",
            ["pdf_bp_stage1"]          = "HTN st. 1",
            ["pdf_bp_stage2"]          = "HTN st. 2",
            ["pdf_bp_crisis"]          = "crisis",

            ["export_title"]           = "Export PDF report",
            ["export_period"]          = "Period:",
            ["export_from"]            = "From:",
            ["export_to"]              = "To:",
            ["export_include"]         = "Include:",
            ["export_inc_schedule"]    = "Medication list",
            ["export_inc_history"]     = "Intake history",
            ["export_inc_pressure"]    = "Blood pressure",
            ["export_inc_finance"]     = "Expenses",
            ["export_path"]            = "File:",
            ["export_browse"]          = "Browse…",
            ["export_default_name"]    = "MedReport_{from}_{to}.pdf",
            ["export_open_after"]      = "Open after saving",
            ["export_btn_save"]        = "💾 Save PDF",
            ["export_quick_7"]         = "7 days",
            ["export_quick_30"]        = "30 days",
            ["export_quick_90"]        = "90 days",
            ["export_quick_year"]      = "Year",
            ["export_done"]            = "PDF saved: {path}",
            ["export_error"]           = "Failed to save PDF: {err}",

            // Interactions
            ["btn_interactions"]               = "⚠ Interactions",
            ["interactions_title"]             = "Drug Interactions",
            ["interactions_disclaimer"]        = "⚠ THIS IS NOT MEDICAL ADVICE. The table contains only well-documented interactions from open sources. It is incomplete and does not account for doses, comorbidities or individual risks. The absence of a pair does NOT mean there is no interaction. Always consult your doctor or pharmacist.",
            ["interactions_summary"]           = "Medications: {n_meds}. Pairs checked: {n_pairs} against {n_rules} rules. Hits: {n_hits}.",
            ["interactions_none"]              = "✅ No known interactions found.",
            ["interactions_sev_high"]          = "HIGH",
            ["interactions_sev_medium"]        = "Medium",
            ["interactions_sev_info"]          = "Info",

            // Reminders
            ["btn_reminders"]                  = "🔔 Reminders",
            ["reminder_on"]                    = "🔔 Reminders ON",
            ["reminder_off"]                   = "🔕 Reminders OFF",
            ["reminder_toast_title"]           = "Time to take medications ({time})",
            ["reminder_toast_msg"]             = "It's time to take:\n{names}",
            ["reminder_missed_title"]          = "Missed doses",
            ["reminder_missed_msg"]            = "Missed today:\n{lines}",
            ["settings_reminders"]             = "Reminders:",
            ["settings_reminders_note"]        = "Notifications for scheduled medication intake.",

            // Tray
            ["tray_show"]                      = "Show",
            ["tray_exit"]                      = "Exit",
            ["tray_hidden_hint"]               = "App minimized to tray. Double-click to open.",

            // Notes
            ["btn_notes"]                      = "📝 Notes",
            ["notes_title"]                    = "Notes",
            ["notes_empty"]                    = "No notes yet",
            ["notes_add_placeholder"]          = "New note…",
            ["notes_delete_confirm"]           = "Delete note?",
            ["notes_color_none"]               = "None",
            ["notes_color_yellow"]             = "Yellow",
            ["notes_color_green"]              = "Green",
            ["notes_color_red"]                = "Red",
            ["notes_color_blue"]               = "Blue",

            ["weekday_short_0"]        = "Mon",
            ["weekday_short_1"]        = "Tue",
            ["weekday_short_2"]        = "Wed",
            ["weekday_short_3"]        = "Thu",
            ["weekday_short_4"]        = "Fri",
            ["weekday_short_5"]        = "Sat",
            ["weekday_short_6"]        = "Sun",
            ["weekday_full_0"]         = "Monday",
            ["weekday_full_1"]         = "Tuesday",
            ["weekday_full_2"]         = "Wednesday",
            ["weekday_full_3"]         = "Thursday",
            ["weekday_full_4"]         = "Friday",
            ["weekday_full_5"]         = "Saturday",
            ["weekday_full_6"]         = "Sunday",
            ["month_gen_1"]            = "January",
            ["month_gen_2"]            = "February",
            ["month_gen_3"]            = "March",
            ["month_gen_4"]            = "April",
            ["month_gen_5"]            = "May",
            ["month_gen_6"]            = "June",
            ["month_gen_7"]            = "July",
            ["month_gen_8"]            = "August",
            ["month_gen_9"]            = "September",
            ["month_gen_10"]           = "October",
            ["month_gen_11"]           = "November",
            ["month_gen_12"]           = "December",
            ["month_nom_1"]            = "January",
            ["month_nom_2"]            = "February",
            ["month_nom_3"]            = "March",
            ["month_nom_4"]            = "April",
            ["month_nom_5"]            = "May",
            ["month_nom_6"]            = "June",
            ["month_nom_7"]            = "July",
            ["month_nom_8"]            = "August",
            ["month_nom_9"]            = "September",
            ["month_nom_10"]           = "October",
            ["month_nom_11"]           = "November",
            ["month_nom_12"]           = "December",
        },

        ["uk"] = new Dictionary<string, string>
        {
            ["app_title"]              = "Прийом ліків",

            // Вкладка «Запитати ШІ»
            ["tab_ask_ai"]     = "Запитати ШІ",
            ["ai_question"]    = "Питання:",
            ["ai_ask"]         = "▶  Запитати",
            ["ai_save_all"]    = "Зберегти все",
            ["ai_clear"]       = "Очистити",
            ["ai_api_keys"]    = "⚙ API ключі",
            ["ai_save"]        = "Зберегти",
            ["ai_copy"]        = "Копіювати",
            ["ai_copied"]      = "Скопійовано в буфер",
            ["ai_quick"]       = "Швидкі питання:",
            ["ai_qb_compat"]   = "Сумісність",
            ["ai_qb_side"]     = "Побічні ефекти",
            ["ai_qb_time"]     = "Час прийому",
            ["ai_q_compat"]    = "Чи можна приймати ці ліки разом і які можливі взаємодії? Ліки: ",
            ["ai_q_side"]      = "Які основні побічні ефекти у препарату? Препарат: ",
            ["ai_q_time"]      = "О якій порі доби і як (до чи після їжі) краще приймати препарат? Препарат: ",
            ["ai_empty_title"] = "Питання порожнє",
            ["ai_empty_msg"]   = "Введіть питання.",
            ["ai_nothing_msg"] = "Немає відповіді для збереження.",
            ["ai_status_wait"] = "⌛ Чекаю відповіді ШІ…",
            ["ai_status_done"] = "✓ Готово!",
            ["ai_status_browser"]="🌐 Відкрито в браузері: {list}",
            ["ai_status_none"] = "Немає вибраних ШІ.",
            ["ai_browser_note"]= "🌐 Питання відкрито в браузері.\nПитання скопійовано в буфер — вставте (Ctrl+V) у чат.\nСкопіюйте відповідь сюди після отримання.",
            ["ai_req_to"]      = "⌛ Запит до {name}…",
            ["ai_err"]         = "❌ Помилка",
            ["ai_stats"]       = "Символів: {chars} | Слів: {words}",
            ["ai_save_header"] = "Відповіді ШІ",
            ["ai_keys_title"]  = "API ключі для ШІ",
            ["ai_keys_save"]   = "Зберегти",
            ["ai_key_claude_link"]     = "Отримати на console.anthropic.com",
            ["ai_key_gemini_link"]     = "Безкоштовно на aistudio.google.com",
            ["ai_key_deepseek_link"]   = "Отримати на platform.deepseek.com",
            ["ai_key_perplexity_link"] = "Отримати на perplexity.ai/settings/api",

            ["app_data_folder"]        = "Тека даних: {path}",
            ["btn_save"]               = "💾 Зберегти",
            ["btn_cancel"]             = "✕ Скасувати",
            ["btn_close"]              = "✕ Закрити",
            ["btn_edit"]               = "✏ Змінити",
            ["btn_delete"]             = "✕ Видалити",
            ["btn_add"]                = "＋ Додати",
            ["btn_today"]              = "Сьогодні",
            ["btn_now"]                = "Зараз",
            ["btn_settings"]           = "⚙ Налаштування",
            ["btn_pressure"]           = "🩺 Тиск",
            ["btn_manage"]             = "📋 Список ліків",
            ["confirm_title"]          = "Підтвердження",
            ["warning_title"]          = "Увага",
            ["error_title"]            = "Помилка",
            ["empty"]                  = "(порожньо)",

            ["tab_schedule"]           = "Розклад",
            ["tab_history"]            = "Історія",
            ["tab_finance"]            = "Фінанси",
            ["tab_pressure"]           = "Тиск",
            ["tab_meds"]               = "Ліки",

            ["schedule_empty"]         = "Список порожній — додайте ліки через «Список ліків»",
            ["schedule_stats"]         = "Прийнято: {taken} з {total}",
            ["schedule_doctor"]        = "лікар: {doctor}",
            ["schedule_course"]        = "курс: {course}",
            ["btn_pharmacy"]           = "🔗 Аптеки",
            ["btn_description"]        = "▸ Опис",
            ["course_label"]           = "Курс: {text}",
            ["course_progress"]        = "Курс: розпочато {start}, день {day} з {total} ({pct}%)",
            ["course_days_left"]       = "ще {n} дн.",
            ["course_finished"]        = "Курс завершено ({start})",
            ["course_show_btn"]        = "Показати",
            ["course_hide_btn"]        = "Сховати",
            ["course_start_btn"]       = "▸ Почати курс",
            ["course_extend_btn"]      = "+ ще днів",
            ["dlg_course_start_title"] = "Почати курс",
            ["dlg_course_start_date"]  = "Дата початку (ДД.ММ.РРРР):",
            ["dlg_course_duration"]    = "Тривалість (днів):",
            ["dlg_course_dur_invalid"] = "Введіть ціле додатне число днів.",
            ["dlg_course_extend_title"]= "Продовжити курс",
            ["dlg_course_extend_days"] = "Додати днів:",
            ["stock_available"]        = "В наявності: {n} табл.",
            ["stock_empty"]            = "Закінчились ⚠",
            ["stock_not_purchased"]    = "Не куплено ⚠",
            ["taken_no_stock_title"]   = "Немає в наявності",
            ["taken_no_stock_msg"]     = "Не можна відмітити прийом: таблетки відсутні.\nСпочатку введіть покупку у вкладці «Фінанси».",

            ["manage_title"]           = "Список ліків",
            ["manage_delete_confirm"]  = "Видалити препарат «{name}»?",

            ["edit_add_title"]         = "Додати препарат",
            ["edit_edit_title"]        = "Редагувати: {name}",
            ["edit_section"]           = "Секція:",
            ["edit_time"]              = "Час:",
            ["edit_time_note"]         = "Прийом:",
            ["edit_name"]              = "Назва:",
            ["edit_subtitle"]          = "Підпис:",
            ["edit_note"]              = "Примітка:",
            ["edit_doctor"]            = "Лікар:",
            ["edit_course"]            = "Курс:",
            ["edit_pharmacy"]          = "Аптека/пошук:",
            ["edit_id"]                = "ID:",
            ["edit_description"]       = "Опис:",
            ["edit_name_required"]     = "Заповніть «Назва».",

            ["settings_title"]               = "Налаштування",
            ["settings_language"]            = "Мова інтерфейсу:",
            ["settings_patient_name"]        = "Ім'я пацієнта:",
            ["settings_lang_note"]           = "Зміни застосовуються миттєво.",
            ["settings_patient_section"]     = "Пацієнт",
            ["settings_patient_fio"]         = "ПІБ:",
            ["settings_patient_dob"]         = "Дата народження:",
            ["settings_patient_gender"]      = "Стать:",
            ["settings_patient_male"]        = "Чоловіча",
            ["settings_patient_female"]      = "Жіноча",
            ["settings_manage_patients"]     = "👥 Управління пацієнтами",
            ["settings_app_mode_section"]    = "Режим запуску",
            ["settings_mode_window"]         = "Тільки вікно",
            ["settings_mode_window_desc"]    = "Застосунок працює тільки поки відкритий. Закриття завершує роботу.",
            ["settings_mode_tray"]           = "Згорнути в трей",
            ["settings_mode_tray_desc"]      = "Закриття згортає до трею. Нагадування працюють у фоні.",
            ["settings_mode_autostart"]      = "Автозапуск Windows",
            ["settings_mode_autostart_desc"] = "Запускається при вході в Windows. Працює в треї.",
            ["settings_mode_hidden"]         = "Тільки у фоні",
            ["settings_mode_hidden_desc"]    = "Запускається приховано, тільки в треї. Вікно не відкривається.",
            ["settings_feature_wip"]         = "Функція в розробці",
            ["settings_theme_section"]       = "Тема оформлення",
            ["settings_theme_dark"]          = "🌙 Темна",
            ["settings_theme_light"]         = "☀ Світла (Windows)",

            ["settings_reminders_section"]   = "🔔 Нагадування",
            ["settings_reminders_visual"]    = "Показувати нагадування про прийом ліків",
            ["settings_reminders_visual_desc"] = "Сповіщення з'являються за кілька хвилин до прийому. При пропуску або після сну ПК — показується зведення пропущених.",
            ["settings_reminders_voice"]     = "🔊 Голосові нагадування",
            ["settings_reminders_voice_desc"] = "Вголос вимовляти назву препарату при настанні часу прийому.",
            ["settings_voice_label"]         = "Голос:",
            ["settings_voice_test"]          = "🔊 Тест",
            ["settings_voice_auto"]          = "(авто)",
            ["settings_voice_test_text"]     = "Час прийняти ліки",
            ["settings_tg_section"]          = "📨 Дублювання в Telegram",
            ["settings_tg_enable"]           = "Надсилати ті самі нагадування в Telegram",
            ["settings_tg_enable_desc"]      = "Зручно, якщо ПК вимкнено або ви не поряд.",
            ["settings_tg_token_label"]      = "Bot Token:",
            ["settings_tg_how"]             = "❓ Як створити бота?",
            ["settings_tg_how_url"]          = "https://t.me/BotFather",
            ["settings_tg_connect"]          = "🔗 Підключити Telegram",
            ["settings_tg_disconnect"]       = "Відключити",
            ["settings_tg_test"]             = "Надіслати «Привіт»",
            ["settings_tg_connected"]        = "✔ підключено",
            ["settings_tg_not_connected"]    = "не підключено",
            ["settings_tg_id_label"]         = " · ID ",
            ["settings_tg_connecting"]       = "Надішліть будь-яке повідомлення боту @{bot} і натисніть ОК.",
            ["settings_tg_connect_ok"]       = "Підключено! Chat ID: {id}",
            ["settings_tg_connect_fail"]     = "Не вдалося отримати chat ID.",
            ["settings_tg_token_invalid"]    = "Невірний Bot Token.",
            ["settings_tg_test_ok"]          = "Повідомлення надіслано!",
            ["settings_tg_test_fail"]        = "Не вдалося надіслати.",
            ["settings_appearance_section"]  = "🎨 Зовнішній вигляд",
            ["settings_border_label"]        = "Колір меж між блоками:",
            ["settings_border_light"]        = "Світлі",
            ["settings_border_medium"]       = "Середні",
            ["settings_border_dark"]         = "Темні",
            ["settings_border_desc"]         = "Впливає на розділові лінії між картками препаратів.",

            ["settings_update_section"]  = "🔄 Оновлення",
            ["settings_update_check"]    = "🔍 Перевірити оновлення",
            ["settings_update_uptodate"] = "Встановлена остання версія.",
            ["settings_update_failed"]   = "Не вдалося перевірити. Перевірте підключення.",

            ["pressure_title"]         = "Артеріальний тиск",
            ["pressure_header"]        = "Артеріальний тиск  {date}",
            ["pressure_pulse"]         = "Пульс",
            ["pressure_sys"]           = "Систолічний",
            ["pressure_dia"]           = "Діастолічний",
            ["pressure_save"]          = "Зберегти",
            ["pressure_history"]       = "Історія вимірювань",
            ["pressure_no_records"]    = "Записів поки немає",
            ["pressure_invalid_sys"]   = "Систолічний (sys): ціле 60–260.",
            ["pressure_invalid_dia"]   = "Діастолічний (dia): ціле 30–180.",
            ["pressure_invalid_pulse"] = "Пульс: ціле 30–220 (або порожньо).",
            ["pressure_out_of_range"]  = "Значення поза звичайним діапазоном. Зберегти все одно?",
            ["pressure_delete_confirm"]  = "Видалити запис від {ts}?",
            ["pressure_sugar"]           = "Цукор",
            ["pressure_invalid_sugar"]   = "Цукор: число 1.0–30.0 ммоль/л (або порожньо).",
            ["pressure_sugar_unusual"]   = "Цукор поза нормальним діапазоном (3–20 ммоль/л). Зберегти?",
            ["pressure_tab_history"]     = "Історія",
            ["pressure_tab_chart"]       = "Графік",
            ["pressure_delete_selected"] = "✕ Видалити обрану",
            ["pressure_no_selection"]    = "Оберіть рядок для видалення",
            ["pressure_col_datetime"]    = "Дата/час",
            ["pressure_col_sys"]         = "Сист.",
            ["pressure_col_dia"]         = "Діаст.",
            ["pressure_col_pulse"]       = "Пульс",
            ["pressure_col_sugar"]       = "Цукор",
            ["pressure_col_category"]    = "Категорія",
            ["pressure_chart_no_data"]   = "Недостатньо даних для графіку (потрібно ≥ 2 записів)",
            ["pressure_chart_sys"]       = "Систолічний",
            ["pressure_chart_dia"]       = "Діастолічний",
            ["pressure_chart_pulse"]     = "Пульс",
            ["pressure_bp_optimal"]      = "Оптимальний",

            ["history_legend_full"]    = "Усі прийняті",
            ["history_legend_partial"] = "Частково",
            ["history_legend_empty"]   = "Пропущено",
            ["history_legend_none"]    = "Немає даних",
            ["history_select_day"]     = "Оберіть день у календарі",
            ["history_day_taken"]      = "Прийнято: {taken} з {total}",
            ["history_day_no_data"]    = "На {date} відміток немає.",

            ["finance_total"]          = "Підсумок",
            ["finance_total_value"]    = "Загальна сума: {amount}",
            ["finance_per_med"]        = "За препаратами",
            ["finance_purchases"]      = "Покупки",
            ["finance_no_purchases"]   = "Покупок поки немає",
            ["finance_add_purchase"]   = "＋ Додати покупку",
            ["finance_date"]           = "Дата:",
            ["finance_med"]            = "Препарат:",
            ["finance_amount"]         = "Сума:",
            ["finance_note"]           = "Примітка:",
            ["finance_amount_required"]= "Сума має бути додатнім числом.",
            ["finance_med_required"]   = "Оберіть препарат.",
            ["finance_delete_confirm"] = "Видалити покупку «{name}» від {date}?",
            ["fin_col_no"]             = "No",
            ["fin_col_med"]            = "Препарат",
            ["fin_col_total"]          = "Підсумок",
            ["fin_currency"]           = "₴",
            ["fin_units"]              = "шт",
            ["fin_total_by_date"]      = "Підсумок по даті",
            ["fin_grand_label"]        = "Підсумок: {amount} {currency}",
            ["fin_grand_label_cnt"]    = "  ({cnt} шт)",
            ["fin_plan_note"]          = "Це план/оцінка. Фактичні витрати — у блоці вище, з «Грошей».",
            ["fin_actual_title"]       = "Фактичні витрати на ліки (з «Грошей»)",
            ["fin_actual_total"]       = "витрачено: {amount} {currency}",
            ["fin_actual_empty"]       = "Записів немає. Витрати ведуться у програмі «Гроші» (категорія «Аптека»).",
            ["fin_actual_no_money"]    = "Програму «Гроші» не встановлено — фактичні витрати недоступні. Тут можна лише планувати.",
            ["fin_actual_open_money"]  = "Відкрити «Гроші»",
            ["fin_actual_hdr_date"]    = "Дата",
            ["fin_actual_hdr_name"]    = "Ліки / стаття",
            ["fin_actual_hdr_account"] = "Рахунок",
            ["fin_actual_hdr_amount"]  = "Сума",
            ["fin_actual_more"]        = "…та ще {n} записів (показано останні 100).",
            ["fin_no_meds"]            = "Додайте ліки до розкладу — вони з'являться тут",
            ["fin_no_dates"]           = "Натисніть «Додати дату» для початку",
            ["btn_add_date"]           = "＋ Додати дату",
            ["btn_del_last"]           = "✕ Видалити останню",
            ["dlg_add_date_title"]     = "Додати дату",
            ["dlg_add_date_label"]     = "Дата (ДД.ММ.РРРР):",
            ["dlg_add_date_empty"]     = "Введіть дату.",
            ["dlg_add_date_dup"]       = "Дата {val} вже є в таблиці.",
            ["dlg_add_date_invalid"]   = "Невірний формат. Використовуйте ДД.ММ.РРРР (пр.: 15.04.2026).",
            ["fin_no_data"]            = "Немає даних",
            ["fin_no_dates_msg"]       = "Немає дат для видалення.",
            ["fin_del_col_title"]      = "Видалити останню дату?",
            ["fin_del_col_msg"]        = "Видалити стовпець {date}?",
            ["fin_del_col_filled"]     = "У цій колонці заповнено рядків: {n}.",
            ["fin_del_col_empty"]      = "Колонка порожня — даних за цей день немає.",

            ["btn_export_pdf"]         = "📄 Звіт PDF",
            ["pdf_title"]              = "Звіт про прийом ліків",
            ["pdf_period"]             = "{from} — {to}",
            ["pdf_footer_generated"]   = "Згенеровано:",
            ["pdf_section_summary"]    = "Підсумок за період",
            ["pdf_section_schedule"]   = "Список препаратів",
            ["pdf_section_history"]    = "Історія прийому",
            ["pdf_section_pressure"]   = "Артеріальний тиск",
            ["pdf_section_finance"]    = "Витрати",
            ["pdf_history_per_med"]    = "За препаратами",
            ["pdf_stat_days_full"]     = "днів — усі прийняті",
            ["pdf_stat_days_partial"]  = "днів — частково",
            ["pdf_stat_days_empty"]    = "днів — пропуск/немає даних",
            ["pdf_stat_overall"]       = "загальний % прийому",
            ["pdf_pressure_avg_sys"]   = "сер. систолічний",
            ["pdf_pressure_avg_dia"]   = "сер. діастолічний",
            ["pdf_pressure_avg_pulse"] = "сер. пульс",
            ["pdf_pressure_count"]     = "усього вимірювань",
            ["pdf_pressure_category"]  = "категорія",
            ["pdf_col_time"]           = "Час",
            ["pdf_col_med"]            = "Препарат",
            ["pdf_col_doctor"]         = "Лікар",
            ["pdf_col_course"]         = "Курс",
            ["pdf_col_date"]           = "Дата",
            ["pdf_col_when"]           = "Дата/час",
            ["pdf_col_taken"]          = "Прийнято",
            ["pdf_col_percent"]        = "%",
            ["pdf_col_visual"]         = "Візуально",
            ["pdf_col_count"]          = "К-сть",
            ["pdf_col_amount"]         = "Сума",
            ["pdf_bp_normal"]          = "норма",
            ["pdf_bp_normal_high"]     = "норм.підвищений",
            ["pdf_bp_high_normal"]     = "вис.нормальний",
            ["pdf_bp_stage1"]          = "АГ I ст.",
            ["pdf_bp_stage2"]          = "АГ II ст.",
            ["pdf_bp_crisis"]          = "криз",

            ["export_title"]           = "Експорт PDF-звіту",
            ["export_period"]          = "Період:",
            ["export_from"]            = "З:",
            ["export_to"]              = "По:",
            ["export_include"]         = "Включити:",
            ["export_inc_schedule"]    = "Список препаратів",
            ["export_inc_history"]     = "Історія прийому",
            ["export_inc_pressure"]    = "Тиск",
            ["export_inc_finance"]     = "Фінанси",
            ["export_path"]            = "Файл:",
            ["export_browse"]          = "Огляд…",
            ["export_default_name"]    = "MedReport_{from}_{to}.pdf",
            ["export_open_after"]      = "Відкрити після збереження",
            ["export_btn_save"]        = "💾 Зберегти PDF",
            ["export_quick_7"]         = "7 днів",
            ["export_quick_30"]        = "30 днів",
            ["export_quick_90"]        = "90 днів",
            ["export_quick_year"]      = "Рік",
            ["export_done"]            = "PDF збережено: {path}",
            ["export_error"]           = "Не вдалося зберегти PDF: {err}",

            // Взаємодії ліків
            ["btn_interactions"]               = "⚠ Взаємодії",
            ["interactions_title"]             = "Взаємодії ліків",
            ["interactions_disclaimer"]        = "⚠ ЦЕ НЕ МЕДИЧНА КОНСУЛЬТАЦІЯ. Таблиця містить лише добре задокументовані взаємодії з відкритих джерел. Вона неповна і не враховує дози, супутні захворювання або індивідуальні ризики. Відсутність пари НЕ означає відсутності взаємодії. Завжди консультуйтесь з лікарем або фармацевтом.",
            ["interactions_summary"]           = "Препаратів: {n_meds}. Перевірено пар: {n_pairs} за {n_rules} правилами. Збігів: {n_hits}.",
            ["interactions_none"]              = "✅ Відомих взаємодій не знайдено.",
            ["interactions_sev_high"]          = "ВИСОКИЙ",
            ["interactions_sev_medium"]        = "Середній",
            ["interactions_sev_info"]          = "Інфо",

            // Нагадування
            ["btn_reminders"]                  = "🔔 Нагадування",
            ["reminder_on"]                    = "🔔 Нагадування УВМ",
            ["reminder_off"]                   = "🔕 Нагадування ВИМК",
            ["reminder_toast_title"]           = "Час приймати ліки ({time})",
            ["reminder_toast_msg"]             = "Пора прийняти:\n{names}",
            ["reminder_missed_title"]          = "Пропущені прийоми",
            ["reminder_missed_msg"]            = "Пропущено сьогодні:\n{lines}",
            ["settings_reminders"]             = "Нагадування:",
            ["settings_reminders_note"]        = "Сповіщення про прийом ліків за розкладом.",

            // Трей
            ["tray_show"]                      = "Показати",
            ["tray_exit"]                      = "Вихід",
            ["tray_hidden_hint"]               = "Додаток згорнуто до трею. Подвійний клік для відкриття.",

            // Нотатки
            ["btn_notes"]                      = "📝 Нотатки",
            ["notes_title"]                    = "Нотатки",
            ["notes_empty"]                    = "Нотаток поки немає",
            ["notes_add_placeholder"]          = "Нова нотатка…",
            ["notes_delete_confirm"]           = "Видалити нотатку?",
            ["notes_color_none"]               = "Немає",
            ["notes_color_yellow"]             = "Жовтий",
            ["notes_color_green"]              = "Зелений",
            ["notes_color_red"]                = "Червоний",
            ["notes_color_blue"]               = "Синій",

            ["weekday_short_0"]        = "Пн",
            ["weekday_short_1"]        = "Вт",
            ["weekday_short_2"]        = "Ср",
            ["weekday_short_3"]        = "Чт",
            ["weekday_short_4"]        = "Пт",
            ["weekday_short_5"]        = "Сб",
            ["weekday_short_6"]        = "Нд",
            ["weekday_full_0"]         = "понеділок",
            ["weekday_full_1"]         = "вівторок",
            ["weekday_full_2"]         = "середа",
            ["weekday_full_3"]         = "четвер",
            ["weekday_full_4"]         = "п'ятниця",
            ["weekday_full_5"]         = "субота",
            ["weekday_full_6"]         = "неділя",
            ["month_gen_1"]            = "січня",
            ["month_gen_2"]            = "лютого",
            ["month_gen_3"]            = "березня",
            ["month_gen_4"]            = "квітня",
            ["month_gen_5"]            = "травня",
            ["month_gen_6"]            = "червня",
            ["month_gen_7"]            = "липня",
            ["month_gen_8"]            = "серпня",
            ["month_gen_9"]            = "вересня",
            ["month_gen_10"]           = "жовтня",
            ["month_gen_11"]           = "листопада",
            ["month_gen_12"]           = "грудня",
            ["month_nom_1"]            = "Січень",
            ["month_nom_2"]            = "Лютий",
            ["month_nom_3"]            = "Березень",
            ["month_nom_4"]            = "Квітень",
            ["month_nom_5"]            = "Травень",
            ["month_nom_6"]            = "Червень",
            ["month_nom_7"]            = "Липень",
            ["month_nom_8"]            = "Серпень",
            ["month_nom_9"]            = "Вересень",
            ["month_nom_10"]           = "Жовтень",
            ["month_nom_11"]           = "Листопад",
            ["month_nom_12"]           = "Грудень",
        },

        ["es"] = new Dictionary<string, string>
        {
            ["app_title"]                    = "Toma de medicamentos",
            ["btn_save"]                     = "💾 Guardar",
            ["btn_cancel"]                   = "✕ Cancelar",
            ["btn_close"]                    = "✕ Cerrar",
            ["btn_edit"]                     = "✏ Editar",
            ["btn_delete"]                   = "✕ Eliminar",
            ["btn_add"]                      = "＋ Agregar",
            ["btn_today"]                    = "Hoy",
            ["btn_now"]                      = "Ahora",
            ["btn_settings"]                 = "⚙ Configuración",
            ["btn_pressure"]                 = "🩺 Presión",
            ["btn_manage"]                   = "📋 Medicamentos",
            ["btn_export_pdf"]               = "📄 Informe PDF",
            ["btn_reminders"]                = "🔔 Recordatorios",
            ["btn_interactions"]             = "⚠ Interacciones",
            ["confirm_title"]                = "Confirmación",
            ["warning_title"]                = "Advertencia",
            ["error_title"]                  = "Error",
            ["tab_schedule"]                 = "Horario",
            ["tab_history"]                  = "Historial",
            ["tab_finance"]                  = "Finanzas",
            ["schedule_stats"]               = "Tomado: {taken} de {total}",
            ["settings_title"]               = "Configuración",
            ["settings_language"]            = "Idioma:",
            ["settings_patient_name"]        = "Nombre del paciente:",
            ["settings_lang_note"]           = "Los cambios se aplican al instante.",
            ["settings_patient_section"]     = "Paciente",
            ["settings_patient_fio"]         = "Nombre completo:",
            ["settings_patient_dob"]         = "Fecha de nacimiento:",
            ["settings_patient_gender"]      = "Género:",
            ["settings_patient_male"]        = "Masculino",
            ["settings_patient_female"]      = "Femenino",
            ["settings_manage_patients"]     = "👥 Gestionar pacientes",
            ["settings_app_mode_section"]    = "Modo de inicio",
            ["settings_mode_window"]         = "Solo ventana",
            ["settings_mode_window_desc"]    = "La app funciona solo con la ventana abierta. Cerrar termina la app.",
            ["settings_mode_tray"]           = "Minimizar a bandeja",
            ["settings_mode_tray_desc"]      = "Cerrar minimiza a la bandeja del sistema. Los recordatorios funcionan en segundo plano.",
            ["settings_mode_autostart"]      = "Inicio automático",
            ["settings_mode_autostart_desc"] = "Inicia con Windows. Se ejecuta en la bandeja del sistema.",
            ["settings_mode_hidden"]         = "Solo en segundo plano",
            ["settings_mode_hidden_desc"]    = "Inicia oculto, solo en bandeja. Sin ventana al inicio.",
            ["settings_feature_wip"]         = "Función en desarrollo",
            ["settings_theme_section"]       = "Tema de apariencia",
            ["settings_theme_dark"]          = "🌙 Oscuro",
            ["settings_theme_light"]         = "☀ Claro (Windows)",
            ["btn_notes"]                      = "📝 Notas",
            ["notes_title"]                    = "Notas",
            ["notes_empty"]                    = "Aún no hay notas",
            ["notes_add_placeholder"]          = "Nueva nota…",
            ["notes_delete_confirm"]           = "¿Eliminar nota?",
            ["notes_color_none"]               = "Ninguno",
            ["notes_color_yellow"]             = "Amarillo",
            ["notes_color_green"]              = "Verde",
            ["notes_color_red"]                = "Rojo",
            ["notes_color_blue"]               = "Azul",
        },

        ["de"] = new Dictionary<string, string>
        {
            ["app_title"]                    = "Medikamenteneinnahme",
            ["btn_save"]                     = "💾 Speichern",
            ["btn_cancel"]                   = "✕ Abbrechen",
            ["btn_close"]                    = "✕ Schließen",
            ["btn_edit"]                     = "✏ Bearbeiten",
            ["btn_delete"]                   = "✕ Löschen",
            ["btn_add"]                      = "＋ Hinzufügen",
            ["btn_today"]                    = "Heute",
            ["btn_now"]                      = "Jetzt",
            ["btn_settings"]                 = "⚙ Einstellungen",
            ["btn_pressure"]                 = "🩺 Blutdruck",
            ["btn_manage"]                   = "📋 Medikamente",
            ["btn_export_pdf"]               = "📄 PDF-Bericht",
            ["btn_reminders"]                = "🔔 Erinnerungen",
            ["btn_interactions"]             = "⚠ Wechselwirkungen",
            ["confirm_title"]                = "Bestätigung",
            ["warning_title"]                = "Warnung",
            ["error_title"]                  = "Fehler",
            ["tab_schedule"]                 = "Zeitplan",
            ["tab_history"]                  = "Verlauf",
            ["tab_finance"]                  = "Finanzen",
            ["schedule_stats"]               = "Genommen: {taken} von {total}",
            ["settings_title"]               = "Einstellungen",
            ["settings_language"]            = "Sprache:",
            ["settings_patient_name"]        = "Patientenname:",
            ["settings_lang_note"]           = "Änderungen werden sofort übernommen.",
            ["settings_patient_section"]     = "Patient",
            ["settings_patient_fio"]         = "Vollständiger Name:",
            ["settings_patient_dob"]         = "Geburtsdatum:",
            ["settings_patient_gender"]      = "Geschlecht:",
            ["settings_patient_male"]        = "Männlich",
            ["settings_patient_female"]      = "Weiblich",
            ["settings_manage_patients"]     = "👥 Patienten verwalten",
            ["settings_app_mode_section"]    = "Startmodus",
            ["settings_mode_window"]         = "Nur Fenster",
            ["settings_mode_window_desc"]    = "Die App läuft nur solange das Fenster offen ist. Schließen beendet die App.",
            ["settings_mode_tray"]           = "In Tray minimieren",
            ["settings_mode_tray_desc"]      = "Schließen minimiert in die Taskleiste. Erinnerungen laufen im Hintergrund.",
            ["settings_mode_autostart"]      = "Windows-Autostart",
            ["settings_mode_autostart_desc"] = "Startet mit Windows. Läuft in der Taskleiste.",
            ["settings_mode_hidden"]         = "Nur im Hintergrund",
            ["settings_mode_hidden_desc"]    = "Startet ausgeblendet, nur im Tray. Kein Fenster beim Start.",
            ["settings_feature_wip"]         = "Funktion in Entwicklung",
            ["settings_theme_section"]       = "Erscheinungsbild",
            ["settings_theme_dark"]          = "🌙 Dunkel",
            ["settings_theme_light"]         = "☀ Hell (Windows)",
            ["btn_notes"]                      = "📝 Notizen",
            ["notes_title"]                    = "Notizen",
            ["notes_empty"]                    = "Noch keine Notizen",
            ["notes_add_placeholder"]          = "Neue Notiz…",
            ["notes_delete_confirm"]           = "Notiz löschen?",
            ["notes_color_none"]               = "Keine",
            ["notes_color_yellow"]             = "Gelb",
            ["notes_color_green"]              = "Grün",
            ["notes_color_red"]                = "Rot",
            ["notes_color_blue"]               = "Blau",
        },

        ["fr"] = new Dictionary<string, string>
        {
            ["app_title"]                    = "Prise de médicaments",
            ["btn_save"]                     = "💾 Enregistrer",
            ["btn_cancel"]                   = "✕ Annuler",
            ["btn_close"]                    = "✕ Fermer",
            ["btn_edit"]                     = "✏ Modifier",
            ["btn_delete"]                   = "✕ Supprimer",
            ["btn_add"]                      = "＋ Ajouter",
            ["btn_today"]                    = "Aujourd'hui",
            ["btn_now"]                      = "Maintenant",
            ["btn_settings"]                 = "⚙ Paramètres",
            ["btn_pressure"]                 = "🩺 Tension",
            ["btn_manage"]                   = "📋 Médicaments",
            ["btn_export_pdf"]               = "📄 Rapport PDF",
            ["btn_reminders"]                = "🔔 Rappels",
            ["btn_interactions"]             = "⚠ Interactions",
            ["confirm_title"]                = "Confirmation",
            ["warning_title"]                = "Attention",
            ["error_title"]                  = "Erreur",
            ["tab_schedule"]                 = "Planning",
            ["tab_history"]                  = "Historique",
            ["tab_finance"]                  = "Finances",
            ["schedule_stats"]               = "Pris : {taken} sur {total}",
            ["settings_title"]               = "Paramètres",
            ["settings_language"]            = "Langue :",
            ["settings_patient_name"]        = "Nom du patient :",
            ["settings_lang_note"]           = "Les modifications s'appliquent immédiatement.",
            ["settings_patient_section"]     = "Patient",
            ["settings_patient_fio"]         = "Nom complet :",
            ["settings_patient_dob"]         = "Date de naissance :",
            ["settings_patient_gender"]      = "Sexe :",
            ["settings_patient_male"]        = "Masculin",
            ["settings_patient_female"]      = "Féminin",
            ["settings_manage_patients"]     = "👥 Gérer les patients",
            ["settings_app_mode_section"]    = "Mode de démarrage",
            ["settings_mode_window"]         = "Fenêtre uniquement",
            ["settings_mode_window_desc"]    = "L'app fonctionne uniquement lorsque la fenêtre est ouverte. Fermer quitte l'app.",
            ["settings_mode_tray"]           = "Réduire dans la barre",
            ["settings_mode_tray_desc"]      = "Fermer réduit dans la barre des tâches. Les rappels fonctionnent en arrière-plan.",
            ["settings_mode_autostart"]      = "Démarrage automatique",
            ["settings_mode_autostart_desc"] = "Démarre avec Windows. S'exécute dans la barre des tâches.",
            ["settings_mode_hidden"]         = "Arrière-plan uniquement",
            ["settings_mode_hidden_desc"]    = "Démarre masqué, dans la barre seulement. Pas de fenêtre au démarrage.",
            ["settings_feature_wip"]         = "Fonctionnalité en développement",
            ["settings_theme_section"]       = "Thème de l'interface",
            ["settings_theme_dark"]          = "🌙 Sombre",
            ["settings_theme_light"]         = "☀ Clair (Windows)",
            ["btn_notes"]                      = "📝 Notes",
            ["notes_title"]                    = "Notes",
            ["notes_empty"]                    = "Aucune note pour l'instant",
            ["notes_add_placeholder"]          = "Nouvelle note…",
            ["notes_delete_confirm"]           = "Supprimer la note ?",
            ["notes_color_none"]               = "Aucun",
            ["notes_color_yellow"]             = "Jaune",
            ["notes_color_green"]              = "Vert",
            ["notes_color_red"]                = "Rouge",
            ["notes_color_blue"]               = "Bleu",
        },

        ["it"] = new Dictionary<string, string>
        {
            ["app_title"]                    = "Assunzione farmaci",
            ["btn_save"]                     = "💾 Salva",
            ["btn_cancel"]                   = "✕ Annulla",
            ["btn_close"]                    = "✕ Chiudi",
            ["btn_edit"]                     = "✏ Modifica",
            ["btn_delete"]                   = "✕ Elimina",
            ["btn_add"]                      = "＋ Aggiungi",
            ["btn_today"]                    = "Oggi",
            ["btn_now"]                      = "Adesso",
            ["btn_settings"]                 = "⚙ Impostazioni",
            ["btn_pressure"]                 = "🩺 Pressione",
            ["btn_manage"]                   = "📋 Farmaci",
            ["btn_export_pdf"]               = "📄 Report PDF",
            ["btn_reminders"]                = "🔔 Promemoria",
            ["btn_interactions"]             = "⚠ Interazioni",
            ["confirm_title"]                = "Conferma",
            ["warning_title"]                = "Attenzione",
            ["error_title"]                  = "Errore",
            ["tab_schedule"]                 = "Orario",
            ["tab_history"]                  = "Cronologia",
            ["tab_finance"]                  = "Finanze",
            ["schedule_stats"]               = "Preso: {taken} di {total}",
            ["settings_title"]               = "Impostazioni",
            ["settings_language"]            = "Lingua:",
            ["settings_patient_name"]        = "Nome del paziente:",
            ["settings_lang_note"]           = "Le modifiche vengono applicate immediatamente.",
            ["settings_patient_section"]     = "Paziente",
            ["settings_patient_fio"]         = "Nome completo:",
            ["settings_patient_dob"]         = "Data di nascita:",
            ["settings_patient_gender"]      = "Sesso:",
            ["settings_patient_male"]        = "Maschile",
            ["settings_patient_female"]      = "Femminile",
            ["settings_manage_patients"]     = "👥 Gestisci pazienti",
            ["settings_app_mode_section"]    = "Modalità di avvio",
            ["settings_mode_window"]         = "Solo finestra",
            ["settings_mode_window_desc"]    = "L'app funziona solo con la finestra aperta. Chiudere termina l'app.",
            ["settings_mode_tray"]           = "Riduci nel tray",
            ["settings_mode_tray_desc"]      = "Chiudere riduce nel tray di sistema. I promemoria lavorano in background.",
            ["settings_mode_autostart"]      = "Avvio automatico Windows",
            ["settings_mode_autostart_desc"] = "Si avvia con Windows. Viene eseguito nel tray di sistema.",
            ["settings_mode_hidden"]         = "Solo in background",
            ["settings_mode_hidden_desc"]    = "Si avvia nascosto, solo nel tray. Nessuna finestra all'avvio.",
            ["settings_feature_wip"]         = "Funzionalità in sviluppo",
            ["settings_theme_section"]       = "Tema dell'interfaccia",
            ["settings_theme_dark"]          = "🌙 Scuro",
            ["settings_theme_light"]         = "☀ Chiaro (Windows)",
            ["btn_notes"]                      = "📝 Note",
            ["notes_title"]                    = "Note",
            ["notes_empty"]                    = "Nessuna nota ancora",
            ["notes_add_placeholder"]          = "Nuova nota…",
            ["notes_delete_confirm"]           = "Eliminare la nota?",
            ["notes_color_none"]               = "Nessuno",
            ["notes_color_yellow"]             = "Giallo",
            ["notes_color_green"]              = "Verde",
            ["notes_color_red"]                = "Rosso",
            ["notes_color_blue"]               = "Blu",
        },
    };

    /// <summary>Месяц в родительном падеже (для «5 мая 2026»).</summary>
    public static string MonthGenitive(int monthNumber)
        => T($"month_gen_{monthNumber}");

    public static string MonthNominative(int monthNumber)
        => T($"month_nom_{monthNumber}");

    /// <summary>0 = понедельник, 6 = воскресенье (ISO).</summary>
    public static string WeekdayShort(int isoDow) => T($"weekday_short_{isoDow}");
    public static string WeekdayFull(int isoDow)  => T($"weekday_full_{isoDow}");

    /// <summary>«5 мая 2026» в текущей локали.</summary>
    public static string FormatDateLong(DateTime d)
        => $"{d.Day} {MonthGenitive(d.Month)} {d.Year}";
}
